/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sarvika.httpserver;

import com.sarvika.httpserver.server.Server;

import java.io.IOException;

public class App {

    public static void main(String[] args) throws IOException {
        if (args.length != 2) {
            System.err.println("usage: server.jar <port> <base dir>");
            System.exit(1);
        }

        int port = Integer.parseInt(args[0]);
        String baseDir = args[1];

        Server sv = new Server(port, baseDir);
        sv.start();
    }
}
