/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sarvika.httpserver;

import com.sarvika.httpserver.server.Server;

import java.io.IOException;

public class App {

    public static void main(String[] args) throws IOException {
        Server sv = new Server(8000);
        sv.start();
    }
}
